### ISSUE TITLE
Getting error when I run :spawn

### ISSUE THREAD

**Issue by furkkurt** [gicrisf/swapforqute#1]
I did everything as documented but when I run `:spawn --userscript swapforqute/main.py`, I am getting `Userscript exited with status 1`. Here is the output of `:process`<br>

![image](https://user-images.githubusercontent.com/69459954/207584428-425afeef-5c12-4c66-aea7-33405474d6b2.png)

**Comment by gicrisf** [comment]
The userscript is rightly installed, but it looks like something's missing in the configuration, since the commands lacks the two required arguments:
- The URL you want to swap;
- The config file.

Probably, there's some problem in the alias: [see this section of the README](https://github.com/gicrisf/swapforqute/#alias-and-keybindings)

**Comment by furkkurt** [comment]
Thanks! Now I don't get any errors but when I run 
`:spawn --userscript ~/.config/qutebrowser/userscripts/swapforqute/main.py -c ~/.config/qutebrowser/userscripts/swapforqute/config.json --cmd 'open' -u reddit.com `
It still opens www.reddit.com not the old reddit. My config.json file looks like this;
```
{
  "www.reddit.com": {
    "out": "old.reddit.com",
    "force_https": true,
    "clean_queries": true
  },
  "reddit.com": {
    "out": "old.reddit.com",
    "force_https": true,
    "clean_queries": true
  }
}
```
What could be the problem here?

**Comment by gicrisf** [comment]
I think you did everything perfectly, but this could happen because the URL is missing the initial `https://` or `http://` substring; the script doesn't transform the URL and pass it directly to qutebrowser. 

My bad, I didn't warned about this behaviour in the Readme because I thought anyone would launch the command from `f` or `F` hints like me, but I definitely should explain this. Thanks for the feedback

**Comment by furkkurt** [comment]
Oh you are right! It successfully  redirects when I enter the link with https and it also works perfectly with your hint alies. Thank you!
